#!/usr/bin/env bash
# Pull secrets from Infisical into local gitignored files for pre-release.
# Never prints secret values.
#
# Requires: infisical CLI logged in (or INFISICAL_TOKEN / machine identity).
# Default project: SHIPPIN_INFISICAL_PROJECT_ID or value from secrets/warden-storage-client.env
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

if ! command -v infisical >/dev/null 2>&1; then
  echo "ERROR: infisical CLI not on PATH" >&2
  exit 1
fi

PROJECT_ID="${SHIPPIN_INFISICAL_PROJECT_ID:-}"
if [ -z "$PROJECT_ID" ] && [ -f secrets/warden-storage-client.env ]; then
  # shellcheck disable=SC1091
  PROJECT_ID="$(grep -E '^SHIPPIN_INFISICAL_PROJECT_ID=' secrets/warden-storage-client.env | head -1 | cut -d= -f2- | tr -d "\"'")"
fi
PROJECT_ID="${PROJECT_ID:-4a897376-3cbd-4aeb-8550-c7d3ed7ad113}"
ENV_NAME="${SHIPPIN_INFISICAL_ENV:-dev}"

echo "== Infisical sync =="
echo "projectId=$PROJECT_ID env=$ENV_NAME (values not printed)"

TMP="$(mktemp)"
if ! infisical secrets --projectId "$PROJECT_ID" --env "$ENV_NAME" --path / --recursive --silent -o json >"$TMP" 2>/tmp/infisical-sync.err; then
  echo "ERROR: infisical secrets failed" >&2
  head -5 /tmp/infisical-sync.err >&2 || true
  rm -f "$TMP"
  exit 1
fi

# Map Infisical keys -> local env file lines (keys only reported)
python3 - "$TMP" "$ROOT/secrets/proxmox.env" <<'PY'
import json, os, sys
from pathlib import Path

src, dest = sys.argv[1], Path(sys.argv[2])
data = json.load(open(src))
items = data if isinstance(data, list) else data.get("secrets") or []
kv = {}
for s in items:
    k = s.get("secretKey") or s.get("key")
    v = s.get("secretValue") or s.get("value")
    if k and v is not None:
        kv[k] = v

# Preferred names + fallbacks for Proxmox
mapping = {
    "PROXMOX_HOST": ["PROXMOX_HOST", "SERVER1_TAILNET_IP", "SERVER1_INTERNAL_IP"],
    "PROXMOX_PORT": ["PROXMOX_PORT"],
    "PROXMOX_NODE": ["PROXMOX_NODE"],
    "PROXMOX_TOKEN_ID": ["PROXMOX_TOKEN_ID", "PVE_TOKEN_ID", "PROXMOX_API_TOKEN_ID"],
    "PROXMOX_TOKEN_SECRET": ["PROXMOX_TOKEN_SECRET", "PVE_TOKEN_SECRET", "PROXMOX_API_TOKEN_SECRET"],
    "PROXMOX_VERIFY_TLS": ["PROXMOX_VERIFY_TLS"],
}

defaults = {
    "PROXMOX_HOST": "10.0.0.1",
    "PROXMOX_PORT": "8006",
    "PROXMOX_NODE": "server1",
    "PROXMOX_VERIFY_TLS": "false",
    "PROXMOX_TOKEN_ID": "",
    "PROXMOX_TOKEN_SECRET": "",
}

found, missing = [], []
out = {}
for dest_key, candidates in mapping.items():
    val = None
    src_key = None
    for c in candidates:
        if c in kv and str(kv[c]).strip() != "":
            val = str(kv[c]).strip()
            src_key = c
            break
    if val is None:
        val = defaults.get(dest_key, "")
        if dest_key in ("PROXMOX_TOKEN_ID", "PROXMOX_TOKEN_SECRET") and not val:
            missing.append(dest_key)
        else:
            found.append(f"{dest_key}=default")
    else:
        found.append(f"{dest_key}<-{src_key}")
    out[dest_key] = val

lines = [
    "# Generated by scripts/dev/sync-secrets-from-infisical.sh — DO NOT COMMIT",
    "# Values loaded from Infisical; never paste into chat.",
]
for k in ["PROXMOX_HOST", "PROXMOX_PORT", "PROXMOX_NODE", "PROXMOX_TOKEN_ID", "PROXMOX_TOKEN_SECRET", "PROXMOX_VERIFY_TLS"]:
    lines.append(f"{k}={out[k]}")

dest.parent.mkdir(parents=True, exist_ok=True)
dest.write_text("\n".join(lines) + "\n")
os.chmod(dest, 0o600)

print("wrote", dest)
print("mapped:", ", ".join(found))
if missing:
    print("MISSING in Infisical (add these keys under project env dev path /):")
    for m in missing:
        print(" ", m)
    print("Suggested Infisical keys: PROXMOX_TOKEN_ID, PROXMOX_TOKEN_SECRET")
    print("Optional: PROXMOX_HOST, PROXMOX_PORT, PROXMOX_NODE, PROXMOX_VERIFY_TLS")
    sys.exit(2)
print("Proxmox credentials present (values redacted).")
PY
rc=$?
rm -f "$TMP"

# Inventory of useful non-secret-adjacent keys present (names only)
echo "-- Infisical keys present that relate to foundation (names only) --"
infisical secrets --projectId "$PROJECT_ID" --env "$ENV_NAME" --path / --silent -o json 2>/dev/null \
  | python3 -c "import sys,json; d=json.load(sys.stdin); ks=sorted((s.get('secretKey')or'') for s in (d if isinstance(d,list) else []));
print('\n'.join(k for k in ks if any(x in k.upper() for x in ['SERVER1','WARDEN','AUTHENTIK','SURREAL','QDRANT','CLOUDFLARE','TAILSCALE'])))" 2>/dev/null || true

exit $rc
