// Router instance. `routeTree.gen.ts` is GENERATED by the TanStack Start / Router
// vite plugin from the files in src/routes/ — do not hand-edit it. It appears
// after the first `npm install && npm run dev`.
import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

export const router = createRouter({ routeTree });

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
